// Class automatically generated by Dev-C++ New Class wizard

#include "inicio.h" // class's header file
#include <time.h>
#include <stdio.h>
#include <stdlib.h>
#include <windows.h>
#include <locale.h>

// class constructor
inicio::inicio()
{
	system("cls");

  system("color 7");  
  int n1;
  printf("Digite um número inteiro\n\n");
  scanf("%d", &n1);  //Declara Variável que recebe o primeiro número do usuário
  
  system("cls");
  
  int n2;
  printf("Agora digite outro\n\n");
  scanf("%d", &n2);  //Declara Variável que recebe o segundo número do usuário

  system("cls");
  /*A partir deste ponto declaramos as variáveis inteiras para as operações e resultado em seguida realizamos as operacões*/
  int soma, subt, mult;
  
  soma = n1 + n2;
  subt = n1 - n2;
  mult = n1 * n2;
  
  printf("%d + %d = %d\n\n", n1, n2, soma);
  printf("%d - %d = %d\n\n", n1, n2, subt);
  printf("%d x %d = %d\n\n", n1, n2, mult);
  
  Sleep(800);  //Pausa do Software
  
  int opcao;  //Menu Funcional
  printf("Presione:\n");
  printf("1. Relizar outra equação | 2. Sobre o software | 3. Sair do programa\n\n");
  
  scanf("%d", &opcao);  //Obtem a escolha do usuário e armazena na variavel (opcao)
  if (opcao==1)
  {
  inicio();
  }
  if (opcao==2)  //Algoritmo da função 2
  { 
  system("cls"); 
  system("color A");                        
  printf("      CCCCC  OOOOO  FFFFF  EEEEE  II  NN    N  AAAAA\n");
  printf("      C      O   O  F      E      II  N N   N  A   A\n");
  printf("      C      O   O  F      E      II  N  N  N  A   A\n");
  printf("      C      O   O  FFF    EEEEE  II  N  N  N  A A A\n");
  printf("      C      O   O  F      E      II  N  N  N  A   A\n");
  printf("      C      O   O  F      E      II  N  N N   A   A\n");
  printf("      CCCCC  OOOOO  F      EEEEE  II  N   N    A   A  Ver. 0.1.4.7\n\n\n");
  printf("Cofeina Calculator é um software open-source desenvolvido com C++\n");
  printf("livre para implementações públicas, e sem fins lucrativos.\n\n");
  printf("Versão 0.1.4.7, Build 2 - 17/12/2016\n\n");
  printf("Este software é fornecido sem garantia e pode ser reditribuído \n");
  printf("trabalhos derivados devem ser acompanhados da licença Apache 2.0\n\n");
  printf("Para saber mais visite - http://www.apache.org/licenses/LICENSE-2.0\n\n\n");
  printf("Contribuintes: Gustavo C.\n\n");
  Sleep(120000);
  }
  if (opcao==3)  //Algoritmo da função 3    
  system("exit");
}

// class destructor
inicio::~inicio()
{
	// insert your code here
}
