// Class automatically generated by Dev-C++ New Class wizard

#ifndef INCIO_H
#define INCIO_H

/*
 * No description
 */
class inicio
{
	public:
		// class constructor
		inicio();
		// class destructor
		~inicio();
};

#endif // INCIO_H
